const fileMapping={
    js:{
        icon:"assets/file/file_type_js_official.svg"
    },
    json:{
        icon:"assets/file/file_type_json.svg"
    },
    md:{
        icon:"assets/file/file_type_markdown.svg"
    },
    txt:{
        icon:"assets/file/file_type_text.svg"
    },
    java:{
        icon:"assets/file/file_type_java.svg"
    },
    go:{
        icon:"assets/file/file_type_go.svg"
    },
    php:{
        icon:"assets/file/file_type_php.svg"
    },
    py:{
        icon:"assets/file/file_type_python.svg"
    },
    sh:{
        icon:"assets/file/file_type_shell.svg"
    },
    c:{
        icon:"assets/file/file_type_c.svg"
    },
    rs:{
        icon:"assets/file/file_type_rust.svg"
    },
    bat:{
        icon:"assets/file/file_type_bat.svg"
    },
    css:{
        icon:"assets/file/file_type_css.svg"
    },
    html:{
        icon:"assets/file/file_type_html.svg"
    },
    sql:{
        icon:"assets/file/file_type_sql.svg"
    }
};


export default fileMapping